services:
  api:
    build: .
    container_name: ping-api
    ports:
      - "3838:3838"
    volumes:
      - ./hosts.json:/app/hosts.json
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
